name: Node CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
